<a href="https://colab.research.google.com/github/TenzingJoseph/CTS-Python/blob/main/Numpy_Exercise_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

In [13]:
arr1 = np.array([7,9,65,33,85,99])
arr1

array([ 7,  9, 65, 33, 85, 99])

Generate a matrix (2D numpy array) of the values:

In [18]:
arr2 = np.array(((1,2,4),(2,3,0),(0,5,1)))
arr2

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

Change the dimensions of this array to another permitted shape

In [19]:
arr2.reshape(9,1) # (Or) arr2.reshape(1,9)

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

Create an array of string numbers, but use dtype to make it an array of floats.

In [23]:
arr3 = np.array(('1','2','3','4'), dtype='float32')
arr3.dtype

dtype('float32')

Transpose the matrix, printing the new size and shape.

In [30]:
arr4 = np.arange(1,10)
arr4 = arr4.reshape(3,3)

In [32]:
arr4.size

9

In [33]:
arr4.shape

(3, 3)

Use the .astype() method to convert the array to boolean.

In [35]:
arr5 = np.eye(5,dtype='int32')
arr5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [36]:
arr5.astype('bool')

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

Create a numpy array with 50 zeros and
Get the first five values

In [40]:
arr6 = np.zeros(50, dtype='int32')
arr6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [41]:
arr6[0:5]

array([0, 0, 0, 0, 0], dtype=int32)

Create a np array of 2 repeated 20 times and Get the last 3 values

In [42]:
arr7 = np.repeat(2,20)
arr7

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
arr7[-3:]

array([2, 2, 2])

Create a numpy array from 0 to 2 $\pi$ in steps of 0.1 and Get the 4th value to the 7th value

In [48]:
import math

In [52]:
arr8 = np.arange(0,2*(math.pi),0.1)
arr8

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [51]:
arr8[4:8]

array([0.4, 0.5, 0.6, 0.7])

Reverse it

In [53]:
np.flip(arr8)

array([6.2, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. ,
       4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7,
       3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4,
       2.3, 2.2, 2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1,
       1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

Only keep every 4th element.

In [60]:
arr8[0::4]

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. ])

Get every 2nd element, starting from the last and moving backwards.

In [61]:
arr8[::-2]

array([6.2, 6. , 5.8, 5.6, 5.4, 5.2, 5. , 4.8, 4.6, 4.4, 4.2, 4. , 3.8,
       3.6, 3.4, 3.2, 3. , 2.8, 2.6, 2.4, 2.2, 2. , 1.8, 1.6, 1.4, 1.2,
       1. , 0.8, 0.6, 0.4, 0.2, 0. ])

Compute min, max, sum, mean, median, variance, and standard deviation of the below array, all to to 2 decimal places.

In [62]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [63]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

In [75]:
roll = np.random.choice(list(range(1,7)),10)
roll

array([1, 1, 2, 3, 6, 6, 4, 1, 2, 4])

Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [77]:
flip = np.random.choice([0,1,1],10)
flip

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1])